Host: "0.0.0.0"
Port: "9090"
Prefix: ""
Mode: "debug"

Mysql:
    Host: "127.0.0.1"
    Port: "3306"
    Username: "root"
    Password: "12345678"
    DBName: "url-shortener"

JWT:
    AccessSecret: "my-secret"
    AccessExpire: 24h

Url:
    DefaultDuration: 24h