server:
    Host: "0.0.0.0"
    Port: "9090"
    Prefix: ""
    Mode: "debug"
    readonly: false
    request_timeout: "5s"
    global_rate_limit_key: "turl_rate_limit"
    global_write_rate: 10000
    global_write_burst: 4000
    stand_alone_read_rate: 20000
    stand_alone_read_burst: 1000

mysql:
    host: "127.0.0.1"
    port: "3306"
    username: "root"
    password: "12345678"
    db_name: "url-shortener"
    max_conn: 25

jwt:
    access_secret: "my-secret"
    access_expire: 24h

url:
    default_duration: 24h

tddl:
    start_num: 700000000
    step: 1000
    seq_name: "turl"

cache:
    redis:
        addr: ["redis:6379"]
        dial_timeout: "5s"
        max_conn: 25
        ttl: 1800s
    remote_cache_ttl: 1800s
    local_cache:
        ttl: 600s
        capacity: 1000000
        max_memory: 512
