# docker-compose.env.yaml
# 如果你希望使用 Docker 运行各种依赖，可以使用这个文件

version: "2.4"

networks:
  url-shortener-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: url-shortener
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    privileged: true
    restart: always
    networks:
      - url-shortener-net
