# docker-compose.env.yaml
# 如果你希望使用 Docker 运行各种依赖，可以使用这个文件

networks:
  urlshortener-net:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: urlshortener
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    privileged: true
    restart: always
    networks:
      - urlshortener-net
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    # 该命令导致启动后不加载module
    # command: ["redis-server" , "--protected-mode", "no"]
    # 持久化
    environment:
      - REDIS_ARGS="--save 10 1"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - urlshortener-net