# docker-compose.env.yaml
# 如果你希望使用 Docker 运行各种依赖，可以使用这个文件

version: "2.4"

networks:
  urlshortener-net:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: urlshortener_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: urlshortener
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    privileged: true
    restart: always
    networks:
      - urlshortener-net
  redis:
      image: redis/redis-stack-server:latest
      container_name: urlshortener_redis
      environment:
        TZ: Asia/Shanghai
      ports:
        - "6379:6379"
      privileged: true
      restart: always
      networks:
        - urlshortener-net