@hostname = http://localhost
@port = 9090
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MzYxMDQ1NjgsImlhdCI6MTczNjAxODE2OH0.N2xIQQS4V5XnyLkks7_JJkJT_2dDIZJKySsc9Pt6W6I
@authorization = Bearer {{token}}
@email = cattle_horse@163.com
@password = Abc123456

### ping
GET {{host}}/ping HTTP/1.1

### Create Url
POST {{host}}/api/url HTTP/1.1
Authorization: {{authorization}}
Content-Type: {{contentType}}

{
    "original_url": "https://www.google.com/search?q=recursion",
	"duration": null
}

### Register
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Login
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Get Urls
GET {{host}}/api/urls?page=1&size=10 HTTP/1.1
Authorization: {{authorization}}