server:
    Host: "0.0.0.0"
    Port: "8080"
    Prefix: ""
    Mode: "debug"
    readonly: false
    request_timeout: "5s"
    global_rate_limit_key: "turl_rate_limit"
    global_write_rate: 10000
    global_write_burst: 4000
    stand_alone_read_rate: 20000
    stand_alone_read_burst: 1000

cors:
    allow_origins: ["http://localhost:3000"]

mysql:
    host: "mysql"
    port: "3306"
    username: "root"
    password: "123456"
    db_name: "urlshortener"
    max_conn: 25

jwt:
    access_secret: "my-secret"
    access_expire: 24h

url:
    default_duration: 24h
    bloom_filter_size: 100000000
    bloom_filter_false_positive_rate: 0.01

tddl:
    start_num: 700000000
    step: 1000
    seq_name: "urlshortener"

cache:
    redis:
        addrs: ["redis:6379"]
        dial_timeout: "5s"
        max_conn: 25
        ttl: 1800s
    remote_cache_ttl: 1800s
    local_cache:
        ttl: 600s
        capacity: 1000000
        max_memory: 512
