version: "2.4"

networks:
  url-shortener-net:
    driver: bridge

services:
  app:
    image: nxofficial/url-shortener:latest
    container_name: url-shortener-app
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - url-shortener-net

  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: url-shortener
      TZ: Asia/Shanghai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    privileged: true
    restart: always
    networks:
      - url-shortener-net

  watchtower:
    image: containrrr/watchtower
    container_name: url-shortener-watchtower
    command: --interval 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 需要将 Docker 的 sock 映射进去以控制 Docker
    restart: always
    networks:
      - url-shortener-net