database:
  host: 0.0.0.0
  port: 3306
  user: root
  password: 123456
  dbname: urlshortener

app:
  env: "development"
  base_url: "http://localhost:8080"
  port: 8080
  context_timeout: 2s
  default_duration: 10h

logger:
  level: info

jwt:
  access_token_secret: access_token_secret
  access_token_duration: 2h
  refresh_token_secret: access_token_secret
  refresh_token_duration: 168h

email:
  password: 
  username: 
  host_address: smtp.mailersend.net
  host_port: 
  subject: "This is my test mail"
  test_mail: 